# Generated by Django 3.0.5 on 2020-05-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christian_blog_app', '0004_auto_20200518_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
