# Generated by Django 3.0.5 on 2020-05-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christian_blog_app', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='article',
        ),
    ]
