# Generated by Django 3.0.5 on 2020-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christian_blog_app', '0008_auto_20200520_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayer',
            old_name='text',
            new_name='prayer',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='author',
        ),
        migrations.AddField(
            model_name='prayer',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
