# Generated by Django 3.0.5 on 2020-05-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christian_blog_app', '0010_auto_20200522_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
