# Generated by Django 3.0.5 on 2020-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christian_blog_app', '0011_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
